# Generated by Django 3.1.5 on 2021-01-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='person',
            name='unit',
        ),
    ]
